apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vitalicset/frontend:latest
        ports:
        - containerPort: 3000